### ISSUE TITLE
UnsatisfiedLinkError on launch

### ISSUE THREAD

**Issue by spypsy** [ProgrammerDan/arionum-java#4]
Hello, I tried compiling the project myself + downloading the .jar from the releases, and in both cases I'm getting the following error when I lunch the .jar:
```
java.lang.UnsatisfiedLinkError: Error looking up function 'encode_ctx': dlsym(0x7fdd64657c70, encode_ctx): symbol not found
	at com.sun.jna.Function.<init>(Function.java:245)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:542)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:528)
	at com.sun.jna.Library$Handler.invoke(Library.java:228)
	at com.sun.proxy.$Proxy0.encode_ctx(Unknown Source)
	at com.programmerdan.arionum.arionum_miner.MappedHasher.go(MappedHasher.java:249)
	at com.programmerdan.arionum.arionum_miner.Hasher.run(Hasher.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.programmerdan.arionum.arionum_miner.AggressiveAffinityThreadFactory$1.run(AggressiveAffinityThreadFactory.java:73)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

My java is very rusty so I don't really know what's happening, was hoping you could help me out

Thanks!

**Comment by ProgrammerDan** [comment]
Hey there,

This project requires a slightly customized argon2i library. General instructions to get off the ground:

1) clone this project

2) `mvn clean package`

3) `chmod +x build-argon.sh`

4) `build-argon.sh`

5) `run.sh`

Explanation:

(1) -- self explanatory (I hope!)

(2) Builds the project and copies the shell scripts from src/main/resources into the "root" project folder.

(3) Makes the build-argon custom script executable.

(4) Executes the build-argon script, which downloads the ProgrammerDan/arionum-argon2 library and builds it. If you're on windows and want locally compile, you can import this project into Visual Studio. Build using Static Release profile to include all dependencies into the .dll.

(5) The run.sh script has been modified by the build-argon script; in this case, it includes a `-Djna.library.path` entry pointing to the location of the custom argon2 library.

Alternatively, just clone and build the arionum-argon2 library as mentioned, and when you run the jar file, include a `-Djna.library.path=/path/to/the/arionum-argon2/library` -- make a softlink form libargon2.so to the libargon2.so.1 file, or a copy, your choice :).

Hope that helps!

**Comment by spypsy** [comment]
I realized I missed a step in your `README` now. 
Thanks for the quick response and the detailed explanation!!

**Comment by ProgrammerDan** [comment]
My pleasure, glad you found the missing step :)
