### ISSUE TITLE
Debian problem

### ISSUE THREAD

**Issue by albertotea** [ProgrammerDan/arionum-java#5]
Hi,
I'm trying to run java miner on debian distro...
After mvn install and executing run.sh I get this error

Update transitioned to new block. Best DL on last block: 9223372036854775807 Difficulty updated to 36938907. New Block Height: 13847. 
Node: http://aropool.com MinDL: 300000  BestDL: 9223372036854775807  Block Height: 13847
      Time on Block: 0s  Inverse Difficulty: 36938907
  Updates:   Last 1518622183s: 0  Failed: 0  Avg Update RTT: 0ms
  Shares:  Attempted: 0  Rejected: 0  Eff: 100,00%  Avg Hash/nonce: 0  Avg Submit RTT: 0ms
  Overall:  Hashes: 0  Mining Time: 0s  Avg Speed: 0,000H/s  Reported Speed: NaNH/s
 Streams  Runs H/run Cur H/s Cur TiC%  Cur WL%  Argon %    Sha %  Shares Finds Reject
Detected thread main death due to error: Unable to load library 'argon2': Native library (linux-x86/libargon2.so) not found in resource path ([file:/home/alberto/arionum-java-master/arionum-miner/arionum-miner-java.jar])
java.lang.UnsatisfiedLinkError: Unable to load library 'argon2': Native library (linux-x86/libargon2.so) not found in resource path ([file:/home/alberto/arionum-java-master/arionum-miner/arionum-miner-java.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at com.programmerdan.arionum.arionum_miner.jna.Argon2Library.<clinit>(Argon2Library.java:24)
	at com.programmerdan.arionum.arionum_miner.MappedHasher.<init>(MappedHasher.java:99)
	at com.programmerdan.arionum.arionum_miner.HasherFactory.createHasher(HasherFactory.java:43)
	at com.programmerdan.arionum.arionum_miner.Miner.start(Miner.java:799)
	at com.programmerdan.arionum.arionum_miner.Miner.main(Miner.java:439)

**Comment by ProgrammerDan** [comment]
Hello friend!

Likely, `build-argon.sh` step failed.

Be sure that you run that step -- it's essential that you locally build the custom argon2i library. If you insist on using your own argon2i library, check the argon2.h and argon2.c files in the custom library and include the pieces of code marked "Arionum customization" into your preferred argon library.

For your immediate needs, I suspect that the following dependencies for local builds were missing: 

`sudo apt-get install make gcc -y`

on some systems, it may also be necessary to install `build-essentials` in a similar fashion.

Let me know if that gets you going!

**Comment by ProgrammerDan** [comment]
Where you able to get the library built as instructed?
