### ISSUE TITLE
Xeon processor issues

### ISSUE THREAD

**Issue by pookey007** [ProgrammerDan/arionum-java#8]
I'm getting the following exception thrown on my Xeon servers when I run any version of the windows code. Latest Java version also installed.

Any help would be most appreciated.

Ouch: thread HashMasher died with error:
java.lang.IllegalArgumentException: Argument value 0x4000000000000000 exceeds na
tive capacity (4 bytes) mask=0xffffffff00000000
        at com.sun.jna.IntegerType.setValue(IntegerType.java:104)
        at com.sun.jna.IntegerType.<init>(IntegerType.java:67)
        at com.sun.jna.platform.win32.WinDef$DWORD.<init>(WinDef.java:144)
        at net.openhft.affinity.impl.WindowsJNAAffinity.setAffinity(WindowsJNAAf
finity.java:94)
        at net.openhft.affinity.Affinity.setAffinity(Affinity.java:160)
        at net.openhft.affinity.AffinityLock.bind(AffinityLock.java:259)
        at net.openhft.affinity.AffinityLock.assignCurrentThread(AffinityLock.ja
va:227)
        at net.openhft.affinity.LockInventory.updateLockForCurrentThread(LockInv
entory.java:222)
        at net.openhft.affinity.LockInventory.acquireLock(LockInventory.java:104
)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:196)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:166)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:144)
        at com.programmerdan.arionum.arionum_miner.AggressiveAffinityThreadFacto
ry$1.run(AggressiveAffinityThreadFactory.java:68)
        at java.lang.Thread.run(Unknown Source)
Depending on the error, you might consider shutting this down.
Ouch: thread HashMasher-2 died with error:
java.lang.IllegalStateException: cpu 62 already bound to Thread[HashMasher-2,5,m
ain]
        at net.openhft.affinity.AffinityLock.bind(AffinityLock.java:244)
        at net.openhft.affinity.AffinityLock.assignCurrentThread(AffinityLock.ja
va:227)
        at net.openhft.affinity.LockInventory.updateLockForCurrentThread(LockInv
entory.java:222)
        at net.openhft.affinity.LockInventory.acquireLock(LockInventory.java:104
)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:196)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:166)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:144)
        at com.programmerdan.arionum.arionum_miner.AggressiveAffinityThreadFacto
ry$1.run(AggressiveAffinityThreadFactory.java:68)
        at java.lang.Thread.run(Unknown Source)
Depending on the error, you might consider shutting this down.

**Comment by ProgrammerDan** [comment]
This is a core library issue in the affinity library I use. Sadly options appear limited for Windows affinity unless I write my own wrapper to the windows libs. Which I might need to do.

In any case I have some code in another branch that will detect for this and disable affinity. If you aren't comfortable building for yourself, I should hopefully have that finished up soon. Been delaying because I don't have good test harnesses for these types of machines.


Thanks for your patience. If curious, check out `investigate` branch.
